name = "quiet-reader"
main = ".svelte-kit/cloudflare-workers/index.js"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".svelte-kit/cloudflare-workers/assets"
binding = "ASSETS"
